In [4]:
countries = ['United States', 'India', 'China', 'Brazil']

In [5]:
countries

['United States', 'India', 'China', 'Brazil']

In [8]:
print(countries[0])
print(countries[1])
print(countries[2])
print(countries[3])

United States
India
China
Brazil

In [9]:
countries[-1]

'Brazil'

In [10]:
countries[-4]

'United States'

In [ ]:
#Slicing 
list_name[start:stop]

In [12]:
countries[0:3]

['United States', 'India', 'China']

In [13]:
countries[0:1]

['United States']

In [14]:
countries[1:]

['India', 'China', 'Brazil']

In [15]:
countries[2:]

['China', 'Brazil']

In [16]:
countries[:2]

['United States', 'India']

Adding elements to a list

In [17]:
countries

['United States', 'India', 'China', 'Brazil']

In [18]:
countries.append('Canada')

In [19]:
countries

['United States', 'India', 'China', 'Brazil', 'Canada']

In [20]:
countries.insert(0, 'Spain')

In [21]:
countries

['Spain', 'United States', 'India', 'China', 'Brazil', 'Canada']

In [24]:
countries_2 = ['UK', 'Germany',  'Austria']

In [25]:
countries + countries_2

['Spain',
 'United States',
 'India',
 'China',
 'Brazil',
 'Canada',
 'UK',
 'Germany',
 'Austria']

In [26]:
nested_list = [countries, countries_2]

In [27]:
nested_list

[['Spain', 'United States', 'India', 'China', 'Brazil', 'Canada'],
 ['UK', 'Germany', 'Austria']]

Removing An Element from a list

In [33]:
#countries = ['United States', 'India', 'China', 'Brazil']

In [29]:
countries.remove('United States')

In [30]:
countries

['Spain', 'India', 'China', 'Brazil', 'Canada']

In [31]:
countries.pop(-1)

'Canada'

In [32]:
countries

['Spain', 'India', 'China', 'Brazil']

In [34]:
del countries[0]

In [35]:
countries

['India', 'China', 'Brazil']

Sorting a list

In [37]:
numbers = [4,3,10,7,1,2]

In [38]:
numbers.sort()

In [39]:
numbers

[1, 2, 3, 4, 7, 10]

In [42]:
numbers = [4,3,10,7,1,2]
numbers.sort(reverse=False)# or True for not sorted or False for sorted
numbers

[1, 2, 3, 4, 7, 10]

Update an Element

In [43]:
numbers[0] = 1000
numbers

[1000, 2, 3, 4, 7, 10]

Copying a list

In [44]:
countries = ['United States', 'India', 'China', 'Brazil']
new_list = countries[:]

In [45]:
new_list

['United States', 'India', 'China', 'Brazil']

In [47]:
countries.copy()

['United States', 'India', 'China', 'Brazil']

In [48]:
new_list_2 = countries.copy()

In [49]:
new_list_2

['United States', 'India', 'China', 'Brazil']

Dictionary in Python

In [50]:
my_dict = {'key1':'value1', 'key2':'value2'}

In [51]:
my_data = {'name':'Frank', 'age':26}

In [52]:
my_data.keys()

dict_keys(['name', 'age'])

In [54]:
my_data.values()

dict_values(['Frank', 26])

In [55]:
my_data.items()

dict_items([('name', 'Frank'), ('age', 26)])

In [56]:
my_data['height'] = 1.7

In [57]:
my_data

{'name': 'Frank', 'age': 26, 'height': 1.7}

In [80]:
my_data.update({'height':1.8})

In [81]:
my_data

{'name': 'Frank', 'age': 26, 'height': 1.8}

In [71]:
my_data.update({'height':1.96})

In [72]:
my_data

{'name': 'Frank', 'age': 26, 'height': 1.96}

Copy a Dictionary

In [82]:
new_dict = my_data.copy()
new_dict

{'name': 'Frank', 'age': 26, 'height': 1.8}

In [77]:
new_dict_2 = my_data

In [73]:
new_dict_2

{'name': 'Frank', 'age': 26, 'height': 1.96}

Remove Elements in List

In [83]:
my_data.pop('name')

'Frank'

In [84]:
my_data

{'age': 26, 'height': 1.8}

In [85]:
del my_data['age']

In [86]:
my_data

{'height': 1.8}

In [88]:
my_data.clear()

In [90]:
my_data

{}

If Statement

In [ ]:
if <condition>:
    <code>
elif <condition>:
    <code>
...
else:
    <code>

In [101]:
age = 24

if age >=18:
    print("You're an adult!")
elif age>=13:
    print("You're a Teenager")
else:
    print("You're a kid")

You're an adult!

For Loop

In [ ]:
for <variable> in <list>:
    <code>

In [103]:
countries

['United States', 'India', 'China', 'Brazil']

In [105]:
for country in countries:
    print(country)

United States
India
China
Brazil

In [106]:
for i, country in enumerate(countries):
    print(i)
    print(country)

0
United States
1
India
2
China
3
Brazil

In [107]:
my_data = {'name':'Frank', 'age':26}
my_data

{'name': 'Frank', 'age': 26}

In [109]:
for key, value in my_data.items():
    print(key)
    print(value)

name
Frank
age
26

Function

In [ ]:
def function(<params>):
    <code>
    return <data>

In [111]:
def sum_values(a, b):
    x = a + b
    return x

In [116]:
sum_values(1, 3) #a function that adds up and returns the addition

4

Built-In Functions

In [117]:
countries = ['United States', 'India', 'China', 'Brazil']
len(countries)

4

In [118]:
max([10, 63, 81, 1, 99])

99

In [119]:
min([10, 63, 81, 1, 99])

1

In [120]:
type(countries)

list

In [122]:
range(1, 10, 2)

range(1, 10, 2)

In [123]:
for i in range(1, 10, 2):#create a loop
    print(i)

1
3
5
7
9

OS Module

In [125]:
import os

In [127]:
os.getcwd()#direction to the folder

'C:\\Users\\Invate\\Downloads\\Data_Science - Project'

In [128]:
os.listdir()#list the elements in the folder of Data_Science - Project

['.git', '.gitattributes', '.ipynb_checkpoints', 'README.md', 'Untitled.ipynb']

In [129]:
os.makedirs("New Folder")#make a new folder in the Data_Science - Project

In [130]:
os.listdir()

['.git',
 '.gitattributes',
 '.ipynb_checkpoints',
 'New Folder',
 'README.md',
 'Untitled.ipynb']

Module

In [131]:
import pandas as pd
import numpy as np

Creating a DataFrame from an Array

Option 1

In [132]:
#creating an array
data = np.array([[1,4], [2,5], [3,6]])

In [134]:
#creating a dataframe
df = pd.DataFrame(data, index=['row1', 'row2', 'row3'],
             columns=['col1', 'col2'])

In [135]:
df

      col1  col2
row1     1     4
row2     2     5
row3     3     6

Option 2

In [136]:
#Create an array with list shape
data = [[1,4], [2,5], [3,6]]

In [138]:
#show the dataFrame
data

[[1, 4], [2, 5], [3, 6]]

In [139]:
#creating a dataframe
df = pd.DataFrame(data, index=['row1', 'row2', 'row3'],
                  columns=['col1', 'col2'])

In [140]:
#showing the dataframe
df

      col1  col2
row1     1     4
row2     2     5
row3     3     6

Creating a DataFrame from a dictionary

In [141]:
#lists used for this example
states = ['California', 'Texas', 'Florida', 'New York']
population = [39613493, 29730311, 21944577, 19299981]

In [142]:
#Storing list within a dictionary
dict_states = {'States':states, 'Population': population}

In [143]:
df_population = pd.DataFrame(dict_states)

In [144]:
#Showing the DF
df_population

       States  Population
0  California    39613493
1       Texas    29730311
2     Florida    21944577
3    New York    19299981

Creating a DataFrame from a csv file

In [157]:
import pandas as pd

# Use a raw string, double backslashes, or forward slashes
df_exams = pd.read_csv(r"C:\Users\Invate\Downloads\Data_Science - Project\Datasets\StudentsPerformance.csv")
#show first 5 rows
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [158]:
df_exams#show full dataset

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86