In [1]:
import pandas as pd

Read a .csv from a URL with pandas

target website : https://football-data.co.uk/data.php

In [3]:
#reading 1 csv file from the website 
df_premier25 = pd.read_csv('https://football-data.co.uk/mmz4281/2526/E0.csv')

In [4]:
#show the df
df_premier25

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,E0,14/03/2026,20:00,West Ham,Man City,1,1,D,1,1,...,2.05,1.80,NaN,NaN,2.05,1.83,1.99,1.79,2.15,1.85
296,E0,15/03/2026,14:00,Crystal Palace,Leeds,0,0,D,0,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.89,1.88,2.01,1.97
297,E0,15/03/2026,14:00,Man United,Aston Villa,3,1,H,0,0,...,1.90,1.95,NaN,NaN,1.93,1.96,1.88,1.90,1.96,2.02
298,E0,15/03/2026,14:00,Nott'm Forest,Fulham,0,0,D,0,0,...,2.00,1.85,NaN,NaN,2.00,1.91,1.92,1.85,2.04,1.93
299,E0,15/03/2026,16:30,Liverpool,Tottenham,1,1,D,1,0,...,1.80,2.00,NaN,NaN,1.85,2.05,1.77,1.96,1.88,2.11

In [5]:
#rename columns 
df_premier25.rename(columns={'FTHG':'home_goals',
                             'FTAG':'away_goals'}, inplace=True)

In [6]:
#show the df
df_premier25

,Div,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,E0,14/03/2026,20:00,West Ham,Man City,1,1,D,1,1,...,2.05,1.80,NaN,NaN,2.05,1.83,1.99,1.79,2.15,1.85
296,E0,15/03/2026,14:00,Crystal Palace,Leeds,0,0,D,0,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.89,1.88,2.01,1.97
297,E0,15/03/2026,14:00,Man United,Aston Villa,3,1,H,0,0,...,1.90,1.95,NaN,NaN,1.93,1.96,1.88,1.90,1.96,2.02
298,E0,15/03/2026,14:00,Nott'm Forest,Fulham,0,0,D,0,0,...,2.00,1.85,NaN,NaN,2.00,1.91,1.92,1.85,2.04,1.93
299,E0,15/03/2026,16:30,Liverpool,Tottenham,1,1,D,1,0,...,1.80,2.00,NaN,NaN,1.85,2.05,1.77,1.96,1.88,2.11

Read .csv file from multiple URLs with Pandas

-https://football-data.co.uk/mmz4281/2526/E0.csv

-https://football-data.co.uk/mmz4281/2526/E1.csv

Link: root + season + league

In [8]:
#link structure
"https://football-data.co.uk/mmz4281/" + "2526" + "/" + "E0" +".csv"

'https://football-data.co.uk/mmz4281/2526/E0.csv'

In [9]:
#create a root variable 
root = "https://football-data.co.uk/mmz4281/"

Multiple Leagues 

-https://football-data.co.uk/mmz4281/2526/E0.csv

-https://football-data.co.uk/mmz4281/2526/E1.csv

-https://football-data.co.uk/mmz4281/2526/E2.csv

-https://football-data.co.uk/mmz4281/2526/E3.csv

-https://football-data.co.uk/mmz4281/2526/EC.csv

In [10]:
#create list of leagues
leagues = ['E0', 'E1', 'E2', 'E3', 'EC']
frames = []#create an empty list 
#looping through leagues, read multiple csv and append it into a list
for league in leagues:
    df = pd.read_csv( root + '2526' + '/' + league + '.csv')
    frames.append(df)#store each df into the frame list adding all legues into one list

In [12]:
len(frames)#this shows use the length of the file such we have 5 files inside this veraible to it works

5

In [17]:
#show 1st, 2nd and 3rf element 
frames[4]

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,EC,09/08/2025,15:00,Altrincham,Aldershot,3,2,H,2,0,...,1.90,1.90,1.92,1.93,1.90,1.90,1.86,1.84,2.00,1.99
1,EC,09/08/2025,15:00,Boreham Wood,Rochdale,0,2,A,0,0,...,2.00,1.80,2.05,1.82,2.02,1.80,1.96,1.75,2.06,1.89
2,EC,09/08/2025,15:00,Brackley Town,Eastleigh,1,0,H,1,0,...,2.00,1.80,2.14,1.72,2.03,1.80,1.96,1.75,2.06,1.84
3,EC,09/08/2025,15:00,Braintree Town,Halifax,3,0,H,2,0,...,1.93,1.88,1.97,1.88,1.93,1.88,1.88,1.82,1.97,1.98
4,EC,09/08/2025,15:00,Gateshead,Southend,0,3,A,0,1,...,1.83,1.98,1.67,2.19,1.83,2.04,1.75,1.96,1.84,2.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
441,EC,14/03/2026,15:00,Tamworth,Carlisle,2,1,H,0,0,...,1.95,1.85,NaN,NaN,1.95,1.85,1.89,1.81,2.02,1.93
442,EC,14/03/2026,15:00,Truro,Hartlepool,0,1,A,0,0,...,1.85,1.95,NaN,NaN,1.85,1.95,1.81,1.88,1.91,2.03
443,EC,14/03/2026,17:30,Eastleigh,Rochdale,1,3,A,0,1,...,1.93,1.88,NaN,NaN,1.93,1.88,1.89,1.81,2.00,1.91
444,EC,14/03/2026,17:30,Morecambe,Braintree Town,1,1,D,0,0,...,1.83,1.98,NaN,NaN,1.85,1.98,1.79,1.91,1.86,2.14
445,EC,14/03/2026,17:30,Scunthorpe,Altrincham,2,1,H,0,1,...,1.80,2.00,NaN,NaN,1.80,2.00,1.76,1.94,1.88,2.07

Multiple Seasons

In [31]:
for season in range(15, 26):# if the season is between 15 - 26
    print(str(season) + str(season+1))#print all season and the following season to come

1516
1617
1718
1819
1920
2021
2122
2223
2324
2425
2526

In [34]:
#create list of leagues
leagues = ['E0', 'E2', 'E3']
frames = []#create an empty list 
#looping through range of seasonsand insert new columns
for league in leagues:
    for season in range(15, 26):#for loop to go through the files and get the seasons
        df = pd.read_csv( root + str(season) + str(season+1) + '/' + league + '.csv')
        df.insert(1, 'season', season)#so add a new column called season by inserting on the df and then show onlt the season year
        frames.append(df)#store each df into the frame list adding all legues into one list

In [35]:
#total frames (11 seasons X 3 leagues)
len(frames)

33

In [41]:
#show 1st and last element (new season column was created)
frames[32]

,Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA,Unnamed: 132
0,E3,25,02/08/2025,15:00,Accrington,Gillingham,1,1,D,0,...,1.88,1.76,2.12,1.98,1.88,1.92,1.83,2.09,1.88,NaN
1,E3,25,02/08/2025,15:00,Barnet,Fleetwood Town,0,2,A,0,...,1.85,2.29,1.65,2.08,1.85,2.00,1.74,2.04,1.93,NaN
2,E3,25,02/08/2025,15:00,Bristol Rvs,Harrogate,0,1,A,0,...,2.03,1.85,2.00,1.85,2.03,1.78,1.96,1.88,2.12,NaN
3,E3,25,02/08/2025,15:00,Cambridge,Cheltenham,1,0,H,0,...,1.88,1.88,1.97,1.98,1.88,1.90,1.83,1.98,2.00,NaN
4,E3,25,02/08/2025,15:00,Chesterfield,Barrow,1,0,H,1,...,2.03,1.79,2.06,1.80,2.07,1.73,2.02,1.87,2.13,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
434,E3,25,14/03/2026,15:00,Crewe,Walsall,0,3,A,0,...,1.85,NaN,NaN,2.00,1.93,1.87,1.85,2.09,1.90,NaN
435,E3,25,14/03/2026,15:00,Fleetwood Town,Tranmere,0,0,D,0,...,1.88,NaN,NaN,1.98,1.88,1.93,1.78,2.07,1.88,NaN
436,E3,25,14/03/2026,15:00,Oldham,Grimsby,1,0,H,0,...,1.98,NaN,NaN,1.88,1.98,1.81,1.93,1.90,2.07,NaN
437,E3,25,14/03/2026,15:00,Shrewsbury,Cheltenham,0,2,A,0,...,1.83,NaN,NaN,2.03,1.83,1.93,1.79,2.14,1.86,NaN
438,E3,25,14/03/2026,15:00,Swindon,Milton Keynes Dons,1,2,A,0,...,2.00,NaN,NaN,1.85,2.06,1.75,1.98,1.92,2.07,NaN